VIDEO_PATH = "violentVideos/3.mp4"
YOLO_MODEL = "yolov8n.pt"

OUTPUT_FOLDER = "fight_screenshots"

MAX_SCREENSHOTS = 3
CAPTURE_INTERVAL = 2
GEMINI_COOLDOWN = 10

PROCESS_EVERY = 10
SPEED_THRESHOLD = 15